version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # dev container
  - package-ecosystem: "docker"
    directory: "/.devcontainer/workspace/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-minor"]

  - package-ecosystem: "docker-compose"
    directory: "/.devcontainer/"
    schedule:
      interval: "monthly"

