version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "phpunit/phpunit"
        update-types: ["version-update:semver-major"]
      - dependency-name: "phpstan/phpstan"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  # dev container
  - package-ecosystem: "docker"
    directory: "/.devcontainer/workspace/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-minor"]
    cooldown:
      default-days: 7

  - package-ecosystem: "docker-compose"
    directory: "/.devcontainer/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7

