version: '3'

services:
  app:
    container_name: BetterVideoRss
    build: .
    environment:
      BVRSS_SELF_URL_PATH: 'http://exmaple.com/'
      BVRSS_YOUTUBE_API_KEY: ''
    ports:
      - '8080:8080'
    volumes:
      - cache:/app/cache
volumes:
  cache:
