version: '3'

services:
  web:
    build: .
    environment:
      BVRSS_SELF_URL_PATH: 'http://exmaple.com/'
      BVRSS_YOUTUBE_API_KEY: ''
    volumes:
      - cache:/var/www/html/cache/
    ports:
      - '8080:80'

volumes:
  cache:
