version: '3'

services:
  app:
    image: ghcr.io/verifiedjoseph/better-video-rss:1.1.0
    container_name: BetterVideoRss
    environment:
      BVRSS_YOUTUBE_API_KEY: ''
      BVRSS_SELF_URL_PATH: 'https://example.com/'
      BVRSS_TIMEZONE: 'Europe/London'
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - cache:/app/cache
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

volumes:
  cache:
