FROM composer:2.9 AS composer
FROM php:8.2-fpm-alpine3.22

RUN apk add --update --no-cache --virtual .build-deps $PHPIZE_DEPS linux-headers \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del -f .build-deps

RUN apk add git

COPY --from=composer /usr/bin/composer /usr/bin/composer
