services:
  workspace:
    build:
      context: ./workspace
    tty: true
    expose:
      - "9000"
    volumes:
      - ../:/better-video-rss
      - vendor:/better-video-rss/vendor
      - ./workspace/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /better-video-rss
    env_file:
      - .env

  nginx:
    image: nginx:1.29-alpine3.22-slim
    ports:
      - 8080:8080
    volumes:
      - ../:/better-video-rss:ro
      - vendor:/better-video-rss/vendor:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    working_dir: /better-video-rss

  httpbin:
    image: ghcr.io/mccutchen/go-httpbin:2.18
    command: ["go-httpbin", "-port", "80"]
    ports:
      - "8081:80"

volumes:
  vendor:
