services:
  workspace:
    build:
      context: ./workspace
    tty: true
    expose:
      - "9000"
    volumes:
      - ../:/better-video-rss
    working_dir: /better-video-rss
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:8080
    volumes:
      - ../:/better-video-rss:ro
    working_dir: /better-video-rss

  httpbin:
    image: mccutchen/go-httpbin:v2.12.0
    ports:
      - "8081:80"
    command: ["go-httpbin", "-port", "80"]
