services:
  workspace:
    build:
      context: ./workspace
    tty: true
    expose:
      - "9000"
    volumes:
      - ../:/better-video-rss
      - vendor:/better-video-rss/vendor
    working_dir: /better-video-rss
    env_file:
      - .env

  nginx:
    image: nginx:1.27-alpine3.20-slim
    ports:
      - 8080:8080
    volumes:
      - ../:/better-video-rss:ro
      - vendor:/better-video-rss/vendor:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    working_dir: /better-video-rss

  httpbin:
    image: mccutchen/go-httpbin:v2.16.0
    command: ["go-httpbin", "-port", "80"]
    ports:
      - "8081:80"

volumes:
  vendor:
