name: Code quality

on:
  pull_request:
    paths:
      - "**.php"
  push:
    branches: [main]
    paths:
      - "**.php"

permissions:
  contents: read

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
        with:
          php-version: '8.2'
          coverage: none

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --no-check-publish"

      - name: Install dependencies with composer
        run: composer install --prefer-dist

      - name: Run PHPStan
        run: composer lint-phpstan

  phpcs:
    name: phpcs

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
        with:
          php-version: '8.2'
          coverage: none
          tools: cs2pr

      - name: Install dependencies with composer
        run: composer install --prefer-dist

      - name: Run PHPStan
        run: composer lint-phpcs-gh-action
