name: Code quality

on:
  pull_request:
    paths:
      - "**.php"
  push:
    branches: main
    paths:
      - "**.php"

permissions:
  contents: read

  phpcs:
    name: phpcs

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup PHP
        uses: shivammathur/setup-php@7fdd3ece872ec7ec4c098ae5ab7637d5e0a96067 # v2.26.0
        with:
          php-version: '8.1'
          tools: cs2pr

      - name: Install dependencies with composer
        run: composer install --prefer-dist

      - name: Run PHPStan
        run: composer lint-phpcs-gh-action
