name: Code quality

on:
  pull_request:
    paths:
      - "**.php"
  push:
    branches: [main]
    paths:
      - "**.php"

permissions:
  contents: read

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup PHP
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2.30.4
        with:
          php-version: '8.1'
          coverage: none

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --no-check-publish"

      - name: Install dependencies with composer
        run: composer install --prefer-dist

      - name: Run PHPStan
        run: composer lint-phpstan

  phpcs:
    name: phpcs

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup PHP
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2.30.4
        with:
          php-version: '8.1'
          coverage: none
          tools: cs2pr

      - name: Install dependencies with composer
        run: composer install --prefer-dist

      - name: Run PHPStan
        run: composer lint-phpcs-gh-action
