name: Code quality

on:
  pull_request:
    paths:
      - "**.php"
  push:
    branches: [main]
    paths:
      - "**.php"

permissions:
  contents: read

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup PHP
        uses: shivammathur/setup-php@7fdd3ece872ec7ec4c098ae5ab7637d5e0a96067 # v2.26.0
        with:
          php-version: '8.1'
          coverage: none

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --no-check-publish"

      - name: Install dependencies with composer
        run: composer install --prefer-dist

      - name: Run PHPStan
        run: composer lint-phpstan

  phpcs:
    name: phpcs

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup PHP
        uses: shivammathur/setup-php@7fdd3ece872ec7ec4c098ae5ab7637d5e0a96067 # v2.26.0
        with:
          php-version: '8.1'
          coverage: none
          tools: cs2pr

      - name: Install dependencies with composer
        run: composer install --prefer-dist

      - name: Run PHPStan
        run: composer lint-phpcs-gh-action
